apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DBHOST: "YW1mcy5teXNxbC5kYXRhYmFzZS5henVyZS5jb20="
  DBUSERNAME: "YW5raXQwOTA3MDE="
  DBPASSWORD: "RHJvd3NzYXBAMzMwMg=="

